name: vector_graphics_compiler
description: A compiler for `package:vector_graphics`.
version: 1.1.8
publish_to: none
homepage: https://github.com/dnfield/vector_graphics

executables:
  vector_graphics_compiler:

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.3.0
  meta: ^1.7.0
  path_parsing: ^1.0.1
  xml: ^6.3.0

  vector_graphics_codec:
    git:
      url: https://github.com/XperiTech/vector_graphics
      path: packages/vector_graphics_codec

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.20.1
  vector_math: ^2.1.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  vector_graphics:
    git:
      url: https://github.com/XperiTech/vector_graphics
      path: packages/vector_graphics

# Uncomment during development
#dependency_overrides:
#  vector_graphics_codec:
#    path: ../vector_graphics_codec
#  vector_graphics:
#    path: ../vector_graphics

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
